# Generated by Django 3.2 on 2021-05-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('انثي', 'انثي')], default=1, max_length=40, verbose_name='النوع'),
            preserve_default=False,
        ),
    ]
