# Generated by Django 3.2 on 2021-05-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_alter_team_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='team',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='team',
            name='password',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook',
            field=models.CharField(max_length=240, verbose_name='عنوان الفيس بوك'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram',
            field=models.CharField(max_length=240, verbose_name='عنوان الانستجرام'),
        ),
        migrations.AlterField(
            model_name='team',
            name='job',
            field=models.CharField(max_length=40, verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='team',
            name='linked_in',
            field=models.CharField(max_length=240, verbose_name='عنوان لينكد ان'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter',
            field=models.CharField(max_length=240, verbose_name='عنوان التويتر'),
        ),
    ]
