# Generated by Django 3.2 on 2021-05-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_auto_20210520_1025'),
        ('team', '0016_alter_team_gender'),
    ]

    operations = [
    ]
