# Generated by Django 3.2 on 2021-05-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('facebook', models.CharField(max_length=240)),
                ('instagram', models.CharField(max_length=240)),
                ('twitter', models.CharField(max_length=240)),
                ('linked_in', models.CharField(max_length=240)),
                ('gender', models.CharField(choices=[('', '')], max_length=40)),
            ],
        ),
    ]
