# Generated by Django 3.2 on 2021-05-20 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210519_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الطالب')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('انثي', 'انثي')], max_length=40, verbose_name='النوع')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('image', models.ImageField(upload_to='profile/', verbose_name='الصورة الشخصية')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_country', to='accounts.country', verbose_name='البلد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
