# Generated by Django 3.2 on 2021-05-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210520_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
