# Generated by Django 3.2 on 2021-05-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_phone'),
        ('accounts', '0006_alter_student_gender'),
    ]

    operations = [
    ]
