# Generated by Django 3.2 on 2021-05-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20210520_1740'),
        ('accounts', '0008_alter_student_gender'),
    ]

    operations = [
    ]
