# Generated by Django 3.2 on 2021-05-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210526_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
