# Generated by Django 3.2 on 2021-06-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(max_length=150, verbose_name='محتوي الرسالة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='/profile/team1.jpg', null=True, upload_to='profile/', verbose_name='الصورة الشخصية'),
        ),
    ]
