# Generated by Django 3.2 on 2021-06-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210606_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='profile/team-1.jpg', null=True, upload_to='profile/', verbose_name='الصورة الشخصية'),
        ),
    ]
