# Generated by Django 3.2 on 2021-05-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_student_phone'),
        ('Book', '0007_auto_20210519_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الكورس')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='صورة الكورس')),
                ('price', models.CharField(max_length=10, verbose_name='السعر')),
                ('duration', models.CharField(max_length=10, verbose_name='مدة الكورس')),
                ('count_lesson', models.IntegerField(max_length=100, verbose_name='عدد الدروس')),
                ('description', models.TextField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='Book.category', verbose_name='قسم الكورس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_student', to='accounts.student', verbose_name='اسم الطالب')),
            ],
        ),
    ]
