# Generated by Django 3.2 on 2021-05-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='count_lesson',
            field=models.CharField(max_length=100, verbose_name='عدد الدروس'),
        ),
    ]
