# Generated by Django 3.2 on 2021-06-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20210606_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='count_lesson',
        ),
    ]
