# Generated by Django 3.2 on 2021-05-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_student_gender'),
        ('Courses', '0002_alter_course_count_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(related_name='students_course', to='accounts.Student'),
        ),
    ]
