# Generated by Django 3.2 on 2021-05-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_auto_20210528_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
