# Generated by Django 3.2 on 2021-06-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_remove_course_count_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_count',
            field=models.IntegerField(null=True),
        ),
    ]
