# Generated by Django 3.2 on 2021-05-29 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_student_gender'),
        ('Trainer', '0003_auto_20210520_1440'),
        ('Courses', '0004_remove_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Trainer_name', to='Trainer.trainer', verbose_name='اسم المدرب'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CoursesRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_register', to='Courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_register', to='accounts.student')),
            ],
        ),
    ]
