# Generated by Django 3.2 on 2021-06-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_course_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
    ]
