# Generated by Django 3.2 on 2021-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_vediourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail_image',
            field=models.ImageField(default=1, upload_to='courses/', verbose_name='صورة الوصف'),
            preserve_default=False,
        ),
    ]
