# Generated by Django 3.2 on 2021-05-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_course_detail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vediourl',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='vedio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Courses.vediourl'),
            preserve_default=False,
        ),
    ]
