# Generated by Django 3.2 on 2021-06-29 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_vediourl_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vediourl',
            name='is_active',
        ),
        migrations.AddField(
            model_name='course',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Tarsh'), (2, '2 - Horrible'), (3, '3 - Terrible'), (4, '4 - Bad'), (5, '5 - Ok'), (6, '6 - Watchable'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Perfect'), (10, '10 - Master Piece')], verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='ملاحظات'),
        ),
    ]
