# Generated by Django 3.2 on 2021-06-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_auto_20210630_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(max_length=10, verbose_name='مدة الكورس'),
        ),
    ]
