# Generated by Django 3.2 on 2021-05-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_auto_20210530_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='vedio',
        ),
        migrations.AddField(
            model_name='vediourl',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vedio_courses', to='Courses.course', verbose_name='الكورس'),
            preserve_default=False,
        ),
    ]
