# Generated by Django 3.2 on 2021-06-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_auto_20210530_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50, verbose_name='العنوان الاول')),
                ('p1', models.CharField(max_length=100, verbose_name='العنوان الفرعي الاول')),
                ('image1', models.ImageField(upload_to='summary/', verbose_name='الصورة الاولي')),
                ('title2', models.CharField(max_length=50, verbose_name='العنوان الثاني')),
                ('p2', models.CharField(max_length=100, verbose_name='العنوان الفرعي الثاني')),
                ('image2', models.ImageField(upload_to='summary/', verbose_name='الصورة الثانية')),
                ('title3', models.CharField(max_length=50, verbose_name='العنوان الثالث')),
                ('p3', models.CharField(max_length=100, verbose_name='العنوان الفرعي الثالث')),
                ('image3', models.ImageField(upload_to='summary/', verbose_name='الصورة الثالثة')),
                ('title4', models.CharField(max_length=50, verbose_name='العنوان الرابع')),
                ('p4', models.CharField(max_length=100, verbose_name='العنوان الفرعي الرابع')),
                ('image4', models.ImageField(upload_to='summary/', verbose_name='الصورة الرابعة')),
                ('title5', models.CharField(max_length=50, verbose_name='العنوان الخامس')),
                ('p5', models.CharField(max_length=100, verbose_name='العنوان الفرعي الخامس')),
                ('image5', models.ImageField(upload_to='summary/', verbose_name='الصورة الخامسة')),
            ],
        ),
    ]
