# Generated by Django 3.2 on 2021-06-05 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0010_summarycourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('address', models.CharField(max_length=150, verbose_name='العنوان')),
                ('phone', models.CharField(max_length=150, verbose_name='رقم الموبيل')),
                ('logo', models.ImageField(upload_to='sponsers/', verbose_name='الشعار')),
            ],
        ),
        migrations.RemoveField(
            model_name='coursesregistration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursesregistration',
            name='student',
        ),
        migrations.DeleteModel(
            name='SummaryCourse',
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image1',
            field=models.ImageField(null=True, upload_to='summary/', verbose_name='الصورة الاولي'),
        ),
        migrations.AddField(
            model_name='course',
            name='image2',
            field=models.ImageField(null=True, upload_to='summary/', verbose_name='الصورة الثانية'),
        ),
        migrations.AddField(
            model_name='course',
            name='image3',
            field=models.ImageField(null=True, upload_to='summary/', verbose_name='الصورة الثالثة'),
        ),
        migrations.AddField(
            model_name='course',
            name='image4',
            field=models.ImageField(null=True, upload_to='summary/', verbose_name='الصورة الرابعة'),
        ),
        migrations.AddField(
            model_name='course',
            name='image5',
            field=models.ImageField(null=True, upload_to='summary/', verbose_name='الصورة الخامسة'),
        ),
        migrations.AddField(
            model_name='course',
            name='p1',
            field=models.CharField(max_length=100, null=True, verbose_name='العنوان الفرعي الاول'),
        ),
        migrations.AddField(
            model_name='course',
            name='p2',
            field=models.CharField(max_length=100, null=True, verbose_name='العنوان الفرعي الثاني'),
        ),
        migrations.AddField(
            model_name='course',
            name='p3',
            field=models.CharField(max_length=100, null=True, verbose_name='العنوان الفرعي الثالث'),
        ),
        migrations.AddField(
            model_name='course',
            name='p4',
            field=models.CharField(max_length=100, null=True, verbose_name='العنوان الفرعي الرابع'),
        ),
        migrations.AddField(
            model_name='course',
            name='p5',
            field=models.CharField(max_length=100, null=True, verbose_name='العنوان الفرعي الخامس'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='title1',
            field=models.CharField(max_length=50, null=True, verbose_name='العنوان الاول'),
        ),
        migrations.AddField(
            model_name='course',
            name='title2',
            field=models.CharField(max_length=50, null=True, verbose_name='العنوان الثاني'),
        ),
        migrations.AddField(
            model_name='course',
            name='title3',
            field=models.CharField(max_length=50, null=True, verbose_name='العنوان الثالث'),
        ),
        migrations.AddField(
            model_name='course',
            name='title4',
            field=models.CharField(max_length=50, null=True, verbose_name='العنوان الرابع'),
        ),
        migrations.AddField(
            model_name='course',
            name='title5',
            field=models.CharField(max_length=50, null=True, verbose_name='العنوان الخامس'),
        ),
        migrations.DeleteModel(
            name='CoursesRegistration',
        ),
        migrations.AddField(
            model_name='course',
            name='sponsers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_sponsers', to='Courses.sponsers', verbose_name='الرعاة'),
        ),
    ]
