# Generated by Django 3.2 on 2021-06-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_summarycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarycourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sammary_course', to='Courses.course', verbose_name='الكورس'),
            preserve_default=False,
        ),
    ]
