# Generated by Django 3.2 on 2021-06-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_student_gender'),
        ('Courses', '0011_auto_20210605_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_joined', to='accounts.Student'),
        ),
    ]
