# Generated by Django 3.2 on 2021-06-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0012_auto_20210603_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='sammary',
        ),
        migrations.AddField(
            model_name='summarycourse',
            name='sammary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sammary_course', to='Courses.course', verbose_name='الملخص'),
            preserve_default=False,
        ),
    ]
