# Generated by Django 3.2 on 2021-06-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0013_auto_20210605_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesregistration',
            name='course',
        ),
        migrations.AddField(
            model_name='coursesregistration',
            name='course',
            field=models.ManyToManyField(related_name='course_register', to='Courses.Course'),
        ),
    ]
