# Generated by Django 3.2 on 2021-06-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0014_auto_20210605_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesregistration',
            name='course',
        ),
        migrations.AddField(
            model_name='coursesregistration',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_register', to='Courses.course'),
            preserve_default=False,
        ),
    ]
