# Generated by Django 3.2 on 2021-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0014_auto_20210603_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('address', models.CharField(max_length=150, verbose_name='العنوان')),
                ('phone', models.CharField(max_length=150, verbose_name='رقم الموبيل')),
                ('logo', models.ImageField(upload_to='sponsers/', verbose_name='الشعار')),
            ],
        ),
    ]
