# Generated by Django 3.2 on 2021-06-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0015_auto_20210605_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='vediourl',
            name='shows',
            field=models.IntegerField(default=0),
        ),
    ]
