# Generated by Django 3.2 on 2021-06-03 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0015_sponsers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sponsers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_sponsers', to='Courses.sponsers', verbose_name='الرعاة'),
            preserve_default=False,
        ),
    ]
