# Generated by Django 3.2 on 2021-05-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('msg_type', models.CharField(max_length=100)),
                ('msg_content', models.TextField(max_length=300)),
            ],
        ),
    ]
