# Generated by Django 3.2 on 2021-05-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msg_content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='msg_type',
            new_name='subject',
        ),
    ]
