# Generated by Django 3.2 on 2021-05-23 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0002_auto_20210523_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 23, 9, 3, 23, 183991, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=300, verbose_name='محتوي الرسالة'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='الموضوع'),
        ),
    ]
