# Generated by Django 3.2 on 2021-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Us', '0003_auto_20210523_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
