# Generated by Django 3.2 on 2021-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default=1, upload_to='Books'),
            preserve_default=False,
        ),
    ]
