# Generated by Django 3.2 on 2021-05-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='auther',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
