# Generated by Django 3.2 on 2021-05-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20210516_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم التصنيف')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='count_of_download',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد التحميلاات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='count_of_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الصفحات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='descripton',
            field=models.TextField(max_length=600, verbose_name='تفاصيل عن الكتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d', verbose_name='رفع الملف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(upload_to='Books', verbose_name='صورة الكتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم الكتاب'),
        ),
    ]
