# Generated by Django 3.2 on 2021-05-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_auto_20210519_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slid2',
            field=models.ImageField(default='default.png', upload_to='Books', verbose_name=' الصوره الثانيه'),
        ),
        migrations.AddField(
            model_name='book',
            name='slid3',
            field=models.ImageField(default='default.png', upload_to='Books', verbose_name=' الصوره الثالثه'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(default='default.png', upload_to='Books', verbose_name='صورة الكتاب'),
        ),
    ]
