# Generated by Django 3.2 on 2021-05-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_book_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='count_of_page',
        ),
    ]
