# Generated by Django 3.2 on 2021-06-29 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_remove_book_count_of_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
