# Generated by Django 3.2 on 2021-05-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Govenorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('انثي', 'انثي')], max_length=40, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='student',
            name='facebook',
            field=models.CharField(max_length=240, verbose_name='الفيس بوك'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='صورة البروفيل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='instagram',
            field=models.CharField(max_length=240, verbose_name='الانستجرام'),
        ),
        migrations.AlterField(
            model_name='student',
            name='linked_in',
            field=models.CharField(max_length=240, verbose_name='لينكدان'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, verbose_name='الاسم '),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=20, verbose_name=' كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الموبيل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='twitter',
            field=models.CharField(max_length=240, verbose_name='التويتر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_name',
            field=models.CharField(max_length=30, verbose_name=' اسم المستخدم'),
        ),
    ]
