# Generated by Django 3.2 on 2021-05-11 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20210512_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='govenorate',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Student.city'),
            preserve_default=False,
        ),
    ]
